<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="drill">
  <!-- safety_distance: Minimum safety distance in [m] by which the collision volumes are expanded and which is enforced during robot motions -->
  <xacro:macro name="drill" params="connected_to:='' arm_id:='panda' rpy:='0 0 0' xyz:='0 0 0' tcp_xyz:='0 0 0.1034' tcp_rpy:='0 0 0' safety_distance:=0 gazebo:=false description_pkg:=franka_description">
    
    <xacro:unless value="${connected_to == ''}">
      <joint name="${arm_id}_drill_joint" type="fixed">
        <parent link="${connected_to}" />
        <child link="${arm_id}_drill" />
        <origin xyz="${xyz}" rpy="${rpy}" />
        <axis xyz="0 0 1"/>
      </joint>
    </xacro:unless>

    <xacro:link_with_sc name="drill" gazebo="${gazebo}">
      <self_collision_geometries>
        <xacro:collision_capsule xyz="0 0 0.04" direction="y" radius="${0.04+safety_distance}" length="0.1" />
        <xacro:collision_capsule xyz="0 0 0.10" direction="y" radius="${0.02+safety_distance}" length="0.1" />
      </self_collision_geometries>
    </xacro:link_with_sc>

    <!-- Define the drill_tcp frame -->
    <link name="${arm_id}_drill_tcp" />
      
    <joint name="${arm_id}_drill_tcp_joint" type="fixed">  <!-- Define the drill_tcp frame -->
      <origin xyz="${tcp_xyz}" rpy="${tcp_rpy}" />
      <parent link="${arm_id}_drill" />
      <child link="${arm_id}_drill_tcp" />
    </joint>
  </xacro:macro>

</robot>
